Use *c_char type for strings passed to C code
faradayio/exec-rs pull request #2
Opened 2017-09-21 09:42 UTC by willnewton

On different architectures the underlying C char type can be
either a signed or unsigned type. Use this type rather than
*i8/u8 in order to avoid errors when building on ARM.

This is my first Rust code so it is quite possible I got something wrong here!

2017-09-21 11:16 UTC, emk requested changes
Thank you for the PR! This looks like an excellent idea.

However, I noticed that the new code is inconsistent, and that it now uses two different techniques to convert Rust strings to C strings.

I would say that the correct method is to use `arg.as_ptr()` everywhere ([documented here](https://doc.rust-lang.org/std/ffi/struct.CString.html#method.as_ptr), and never go through `as_bytes_with_nul`. See the notes below.

And congratulations on your first Rust PR! It looks great.!

2017-09-21 11:16 UTC, emk commented on src/lib.rs
> +        arg.as_bytes_with_nul().as_ptr() as *const c_char
Here we call `.as_bytes_with_nul().as_ptr() as *const c_char`. We should change this to a plain `.as_ptr()`.

2017-09-21 11:16 UTC, emk commented on src/lib.rs
> +        libc::execvp(program_cstring.as_ptr(), arg_charptrs.as_ptr())
Here we omit `as_bytes_with_nul()`, and call `as_ptr` directly without a cast. This is great as is!

2017-09-21 11:16 UTC, emk commented on src/lib.rs
> +use std::os::raw::c_char;
This will no longer be needed once the suggested changes are made.

2017-09-21 11:39 UTC, willnewton commented
Thanks for the feedback, I'll re-push with your suggestions.

2017-09-22 11:09 UTC, emk approved these changes
Looks great!

2017-09-22 11:10 UTC, merged